# Generated by Django 3.1.7 on 2021-03-17 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoffeeMachine',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50)),
                ('water_line_compatible', models.BooleanField()),
                ('type', models.CharField(choices=[('L', 'Large'), ('S', 'Small'), ('E', 'Espresso')], max_length=1)),
                ('edition', models.CharField(choices=[('B', 'Base'), ('P', 'Premium'), ('D', 'Deluxe')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='CoffeePod',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('sku', models.CharField(max_length=50)),
                ('size', models.IntegerField(choices=[(1, 'One'), (3, 'Three'), (5, 'Five'), (7, 'Seven')])),
                ('type', models.CharField(choices=[('L', 'Large'), ('S', 'Small'), ('E', 'Espresso')], max_length=1)),
                ('flavor', models.CharField(choices=[('V', 'Vanilla'), ('C', 'Carmel'), ('P', 'Psl'), ('M', 'Mocha'), ('H', 'Hazelnut')], max_length=1)),
            ],
        ),
    ]
